### ISSUE TITLE
Error drawing barchart

### ISSUE THREAD

**Issue by robertovaldesperez** [ignoreintuition/v-chart-plugin#194] opened 2021-01-13 15:20 UTC
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

import Chart from 'v-chart-plugin'
Vue.use(Chart)

`<v-chart v-if="listLoading" :chart-data="barChartData" />`

**Comment by ignoreintuition** [comment] 2021-01-14 16:41
Duplicate of another issue

**Comment by robertovaldesperez** [comment] 2021-01-14 18:02
I'm sorry

**Closed** 2021-01-14 18:02 UTC
